id: ICE15D2E5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T06:53:53+00:00'
last_modified: '2022-06-09T07:01:39.391540+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21898
  title: ཡོངས་འཛིན་པཎྜི་ཏ་ཡེ་ཤེས་རྒྱལ་མཚན་གྱི་རྟོགས་བརྗོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    2F63:
      image_group_id: I1PD36389
      title: Volume 1 of yongs 'dzin paN+Di ta ye shes rgyal mtshan gyi rtogs brjod
      total_pages: 242
      order: 1
      base_file: 2F63.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
