id: P007883
initial_creation_type: ocr
source_metadata:
  id: bdr:W21898
  title: ཡོངས་འཛིན་པཎྜི་ཏ་ཡེ་ཤེས་རྒྱལ་མཚན་གྱི་རྟོགས་བརྗོད
  author: ''
  volumes:
    46586733681846f1a2014933664dab5c:
      image_group_id: I1PD36389
      title: ''
      volume_number: 1
      total_pages: 242
ebook_metadata:
  title: ཡོངས་འཛིན་པཎྜི་ཏ་ཡེ་ཤེས་རྒྱལ་མཚན་གྱི་རྟོགས་བརྗོད
  author: ''
  sku: P007883
  cover: cover.jpg
  layers:
  - pagination
