id: P007883
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W21898
  title: ཡོངས་འཛིན་པཎྜི་ཏ་ཡེ་ཤེས་རྒྱལ་མཚན་གྱི་རྟོགས་བརྗོད
  author: ''
  volumes:
    53d048c4ea5a41abad5dc3d56339c6df:
      image_group_id: I1PD36389
      title: Volume 1 of yongs 'dzin paN+Di ta ye shes rgyal mtshan gyi rtogs brjod
      volume_number: 1
      total_pages: 242
      base_file: v001.txt
